---
title: "Investigating Toronto City Council Attendance"
subtitle: "Determining the Ideal Meeting Types and Months for the 2022-2026 Term"
author: 
  - Wendy Yuan
date: "27 September 2024"
date-format: long
abstract: "This paper looks at Toronto City Council attendance data and when meeting absences are highest and lowest. It specifically examines that evening meeting have greater absence rate compared to morning and afternoon. 2022 showed very little absences while 2023 showed many missed attendances. Additionally, March, May, July, and October have are greater proportion of absences - showing a pattern that every couple months has less attendance."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(dplyr)

cleaned_data <- read_csv(here::here("data/cleaned_data/cleaned_data.csv"))
```

\newpage

# Introduction



# Data {#sec-data}



```{r}
#| label: fig-count
#| fig-cap: Count of Number of Sessions per Year, Month, & Type
#| echo: false

table(cleaned_data$session_type)

cleaned_data$session_month <- factor(cleaned_data$session_month, levels = month.abb)
table(cleaned_data$session_month)

table(cleaned_data$session_year)
```



```{r}
#| label: fig-session_type
#| fig-cap: Comparison of Attendance in Morning, Afternoon, vs Evening Session
#| echo: false

ggplot(cleaned_data, aes(x = session_type, fill = present)) +
  geom_bar(position = "dodge2") + 
  labs(
    title = "Present vs Absence in Different Session Types",
    x = "Session Type",
    y = "Count"
  )
```



```{r}
#| label: fig-session_month
#| fig-cap: Comparison of Attendance over Different Months
#| echo: false

cleaned_data |> 
  ggplot(aes(x = session_month, fill = present)) +
  geom_bar(position = "dodge2") + 
  labs(
    title = "Present vs Absence Over Different Months",
    x = "Months",
    y = "Count"
  )
```



```{r}
#| label: fig-session_year
#| fig-cap: Comparison of Attendance between 2022 to 2024
#| echo: false

cleaned_data |> 
  ggplot(aes(x = session_year, fill = present)) +
  geom_bar(position = "dodge") + 
  labs(
    title = "Present vs Absence Over Different Years",
    x = "Years",
    y = "Count"
  )
```



\newpage

# References
